#include <algorithm>
#include <cassert>
#include <iostream>
#include <vector>

using namespace std;

// Problem: Given sorted array, find all combinations summing to S
// Also handle unsorted array case
//
// Memory layout example for arr=[1,2,3,4,5]:
// 0x100: |1|2|3|4|5|
// idx:    0 1 2 3 4
//
// For S=7, valid combinations: {1,2,4}, {2,5}, {3,4}
// Verify: 1+2+4=7, 2+5=7, 3+4=7

// For SORTED array
// Time: O(2^n) worst case, but pruning reduces when sum > target
// Space: O(n) recursion stack + O(n * k) for k results of avg size n
void findCombinationsSorted(vector<int> &arr, int target, int start,
                            int currentSum, vector<int> &current,
                            vector<vector<int>> &result) {
  // TODO: Implement backtracking
  //
  // Trace for arr=[1,2,3,4,5], target=7:
  // call(start=0, sum=0, curr=[])
  //   i=0: 0+1=1<=7, push(1), call(start=1, sum=1, curr=[1])
  //     i=1: 1+2=3<=7, push(2), call(start=2, sum=3, curr=[1,2])
  //       i=2: 3+3=6<=7, push(3), call(start=3, sum=6, curr=[1,2,3])
  //         i=3: 6+4=10>7 PRUNE (sorted -> all remaining >=4)
  //         sum=6!=7, return
  //       pop(3)
  //       i=3: 3+4=7=target -> push(4), call(...), OUTPUT [1,2,4]
  //       ...
  //
  // Key insight: start=i+1 in recursive call, NOT start=0
  // Why: start=0 would reuse arr[0],arr[1],... -> invalid combinations
  //
  // Duplicate handling: if arr has duplicates like [1,1,2]
  // Skip when: i > start AND arr[i] == arr[i-1]
  // Why: arr[0]=1 and arr[1]=1 would both generate same combinations
  //
  // Pruning: if currentSum + arr[i] > target -> break (not continue)
  // Why: arr sorted -> arr[i+1] >= arr[i] -> sum would only increase

  for (size_t i = start; i < arr.size(); i++) {
    if (currentSum + arr[i] > target) {
      return;
    }

    // Skip duplicate values at same recursion level
    // i=0: arr[-1] undefined, i>start prevents this
    // i=1: if arr[1]==arr[0], subsets starting with arr[1] already generated by
    // i=0
    if (i > static_cast<size_t>(start) && arr[i] == arr[i - 1]) {
      continue;
    }

    current.push_back(arr[i]);

    if (currentSum + arr[i] == target) {
      result.push_back(current);
    } else {
      findCombinationsSorted(arr, target, i + 1, currentSum + arr[i], current,
                             result);
    }

    current.pop_back();
  }
}

// For UNSORTED array - approach: sort first, then use sorted algorithm
void findCombinationsUnsorted(vector<int> arr, int target,
                              vector<vector<int>> &result) {
  // Sort array first
  // Why sort? Two reasons:
  // 1. Enables early termination (pruning) when sum > target
  // 2. Enables duplicate skipping with simple i-1 comparison
  sort(arr.begin(), arr.end());

  vector<int> current;
  findCombinationsSorted(arr, target, 0, 0, current, result);
}

// Wrapper for sorted array
vector<vector<int>> findAllCombinationsSorted(vector<int> &arr, int target) {
  vector<vector<int>> result;
  vector<int> current;
  findCombinationsSorted(arr, target, 0, 0, current, result);
  return result;
}

// Wrapper for unsorted array
vector<vector<int>> findAllCombinationsUnsorted(vector<int> arr, int target) {
  vector<vector<int>> result;
  findCombinationsUnsorted(arr, target, result);
  return result;
}

// Helper to print combinations
void printCombinations(const vector<vector<int>> &combinations) {
  cout << "{ ";
  for (size_t i = 0; i < combinations.size(); i++) {
    cout << "[";
    for (size_t j = 0; j < combinations[i].size(); j++) {
      cout << combinations[i][j];
      if (j < combinations[i].size() - 1)
        cout << ",";
    }
    cout << "]";
    if (i < combinations.size() - 1)
      cout << ", ";
  }
  cout << " }" << endl;
}

// Helper to verify sum of each combination equals target
bool verifyCombinations(const vector<vector<int>> &combinations, int target) {
  for (const auto &combo : combinations) {
    int sum = 0;
    for (int x : combo)
      sum += x;
    if (sum != target)
      return false;
  }
  return true;
}

int main() {
  cout << "=== Subset Sum Combinations Tests ===" << endl;

  // Test 1: Basic sorted array
  // arr=[1,2,3,4,5], S=7
  // Expected: {1,2,4}, {2,5}, {3,4}
  // Verify: 1+2+4=7, 2+5=7, 3+4=7
  {
    vector<int> arr = {1, 2, 3, 4, 5};
    int target = 7;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 1 - arr=[1,2,3,4,5], S=7: ";
    printCombinations(result);
    assert(verifyCombinations(result, target));
    assert(result.size() == 3); // {1,2,4}, {2,5}, {3,4}
  }

  // Test 2: Array with duplicates
  // arr=[1,1,2,3], S=4
  // Expected: {1,1,2}, {1,3} (only one {1,3}, not duplicate)
  // Trace: [1,1,2]=4, [1,3]=4, skip second [1,3]
  {
    vector<int> arr = {1, 1, 2, 3};
    int target = 4;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 2 - arr=[1,1,2,3], S=4: ";
    printCombinations(result);
    assert(verifyCombinations(result, target));
    assert(result.size() == 2); // {1,1,2}, {1,3}
  }

  // Test 3: No valid combinations
  // arr=[2,4,6,8], S=5
  // All elements even, 5 odd -> 0 combinations
  {
    vector<int> arr = {2, 4, 6, 8};
    int target = 5;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 3 - arr=[2,4,6,8], S=5: ";
    printCombinations(result);
    assert(result.size() == 0);
  }

  // Test 4: Single element equals target
  // arr=[7], S=7
  // Expected: {7}
  {
    vector<int> arr = {7};
    int target = 7;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 4 - arr=[7], S=7: ";
    printCombinations(result);
    assert(result.size() == 1);
    assert(result[0] == vector<int>{7});
  }

  // Test 5: Empty array
  // arr=[], S=5
  // Expected: {} (no combinations)
  {
    vector<int> arr = {};
    int target = 5;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 5 - arr=[], S=5: ";
    printCombinations(result);
    assert(result.size() == 0);
  }

  // Test 6: All elements same, multiple valid combinations
  // arr=[5,5,5,5], S=10
  // Expected: {5,5} (only one, duplicates skipped)
  {
    vector<int> arr = {5, 5, 5, 5};
    int target = 10;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 6 - arr=[5,5,5,5], S=10: ";
    printCombinations(result);
    assert(verifyCombinations(result, target));
    assert(result.size() == 1); // only one {5,5}
  }

  // Test 7: Target larger than sum of all elements
  // arr=[1,2,3], S=100
  // Sum of all = 6 < 100 -> 0 combinations
  {
    vector<int> arr = {1, 2, 3};
    int target = 100;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 7 - arr=[1,2,3], S=100: ";
    printCombinations(result);
    assert(result.size() == 0);
  }

  // Test 8: Target equals sum of all elements
  // arr=[1,2,3,4], S=10
  // 1+2+3+4=10 -> {1,2,3,4}
  {
    vector<int> arr = {1, 2, 3, 4};
    int target = 10;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 8 - arr=[1,2,3,4], S=10: ";
    printCombinations(result);
    assert(verifyCombinations(result, target));
    // {1,2,3,4} is one valid, check if there are others
  }

  // Test 9: Unsorted array
  // arr=[3,1,4,2], S=5
  // After sorting: [1,2,3,4], combinations: {1,4}, {2,3}
  {
    vector<int> arr = {3, 1, 4, 2};
    int target = 5;
    auto result = findAllCombinationsUnsorted(arr, target);
    cout << "Test 9 - arr=[3,1,4,2], S=5 (unsorted): ";
    printCombinations(result);
    assert(verifyCombinations(result, target));
    assert(result.size() == 2); // {1,4}, {2,3}
  }

  // Test 10: Target is zero
  // arr=[1,2,3], S=0
  // Only empty set sums to 0, but problem asks for "combinations of array
  // elements" Interpretation: no combination of 1+ elements sums to 0 -> 0
  // results
  {
    vector<int> arr = {1, 2, 3};
    int target = 0;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 10 - arr=[1,2,3], S=0: ";
    printCombinations(result);
    // Depends on interpretation: empty set {} or no results
  }

  // Test 11: Large valid set
  // arr=[1,2,3,4,5,6,7,8,9,10], S=15
  // Multiple combinations exist
  {
    vector<int> arr = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int target = 15;
    auto result = findAllCombinationsSorted(arr, target);
    cout << "Test 11 - arr=[1..10], S=15: ";
    cout << result.size() << " combinations found" << endl;
    assert(verifyCombinations(result, target));
  }

  cout << "\n=== All tests passed ===" << endl;
  return 0;
}
